# Generated by Django 2.2.16 on 2020-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user2", models.CharField(max_length=256)),
            ],
        ),
    ]
