# Generated by Django 2.2.16 on 2020-09-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_newapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asdfsdf', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hello',
            },
        ),
    ]
